pipeline {
   agent any
    stages {
        stage('Build') {
            steps {
                //sh 'mvn -B -DskipTests clean package'
               echo "Build"
            }
        }
        stage('Test') {
            steps {
                //sh 'mvn test'
                echo "Test"
            }
            // post {
            //     always {
            //         junit 'target/surefire-reports/*.xml'
            //     }
            // }
        }
        stage('Deliver') {
            steps {
                //sh './jenkins/scripts/deliver.sh'
                echo "Deliver"
            }
        }
    }
}
